Refactored graph viewer page
TwigSlot/twig-client pull request #3
Opened 2022-08-11 15:33 UTC by tch1001

Removed all previous code from neo4j client and replace with basic graph explorer from v-network-graph

2022-08-12 03:30 UTC, xiurobert requested changes
Some cleanup needed

2022-08-12 03:30 UTC, xiurobert commented on src/graphData.ts
> +}
Delete these

2022-08-12 06:37 UTC, xiurobert requested changes

2022-08-12 06:37 UTC, xiurobert commented on src/App.vue
> +            <label class="label" for="server-url">Username/Email:</label>
We don't need the colon here

2022-08-12 06:37 UTC, xiurobert commented on src/App.vue
> +              <input class="input" type="text" id="server-url" value="" />
Also, this id should not be `#server-url` anymore

2022-08-12 06:37 UTC, xiurobert commented on src/App.vue
> +              <input class="input" type="password" id="server-password" value=""/>
Ditto.

2022-08-12 06:37 UTC, xiurobert commented on src/App.vue
> +            <!-- TODO login with google -->
Create a task in the project board for this instead

2022-08-12 06:37 UTC, xiurobert commented on src/App.vue
> +const eventHandlers = graphData.eventHandlers
Is this a requirement by `v-network-graph`? Otherwise, it would be cleaner to shove them into a dictionary

2022-08-12 11:11 UTC, tch1001 commented
Ready for review @xiurobert

2022-08-12 11:13 UTC, xiurobert requested changes

2022-08-12 11:13 UTC, xiurobert commented on src/graphData.ts
> +    //   // console.log(type, event)
Can we delete these

2022-08-13 06:33 UTC, xiurobert approved these changes

2022-08-13 06:34 UTC, merged

2022-08-13 08:56 UTC, xiurobert commented
You should re open this PR @tch1001